# Generated by Django 5.0.4 on 2024-05-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_order_brandphone_alter_order_shipped'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSen',
            fields=[
                ('idOrder', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(blank=True)),
                ('guarantee', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='', max_length=500)),
                ('price', models.FloatField(default=0.0)),
                ('phoneNumber', models.CharField(blank=True, default='', max_length=30)),
                ('nameCustomer', models.CharField(default='', max_length=100)),
                ('surnameCustomer', models.CharField(blank=True, default='', max_length=100)),
                ('pieceName', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='lav', max_length=4)),
                ('modelPhone', models.CharField(default='', max_length=50)),
                ('defect', models.TextField(default='', max_length=100)),
                ('shipped', models.CharField(default='No', max_length=3)),
                ('clientAdviser', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped',
            field=models.CharField(default='Mag', max_length=3),
        ),
    ]
